/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    BreadcrumbComponent: typeof import('./src/app/shared/components/BreadcrumbComponent.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DataView: typeof import('primevue/dataview')['default']
    DataViewLayoutOptions: typeof import('primevue/dataviewlayoutoptions')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    EventsComponent: typeof import('./src/app/events/components/EventsComponent.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginComponent: typeof import('./src/app/user/components/LoginComponent.vue')['default']
    Password: typeof import('primevue/password')['default']
    RegisterComponent: typeof import('./src/app/user/components/RegisterComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
    SidebarComponent: typeof import('./src/app/shared/components/SidebarComponent.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    ToolbarComponent: typeof import('./src/app/shared/components/ToolbarComponent.vue')['default']
  }
}
